### ISSUE TITLE
Allow using WSL for clang-format

### ISSUE THREAD

**Issue by jbayardo** [xaverh/vscode-clang-format#79]
In principle, it should be as easy as calling `wsl clang-format`. I get a:

> The 'wsl clang-format' command is not available. Please check your clang-format.executable user setting and ensure it is installed.

When configuring the executable as that command.

**Comment by xaverh** [comment]
Closed due to inactivity and lack of interest. If you or anyone else still needs this, feel free to send a patch, I will not implement this myself since I don’t have a need for this and don’t really see the point of this since clang-format is running on Windows natively.
