### ISSUE TITLE
Feature request: Clang-format > Language > C#

### ISSUE THREAD

**Issue by aganm** [xaverh/vscode-clang-format#95]
Clang-format claims it can format c# code, I would much rather use it than omnisharp. Omnisharp is missing a fundamental code formatting feature which makes it useless to me.

**Comment by aganm** [comment]
Seems to be working, just had to restart.

**Comment by plinehan** [comment]
This is awesome! Would it be possible to do a new release to the Marketplace to pick up this change?

**Comment by Icantjuddle** [comment]
> This is awesome! Would it be possible to do a new release to the Marketplace to pick up this change?

Just double checking on this, would love to be able to use this with my C# code.

**Comment by lonix1** [comment]
Yeah push to marketplace please :pray:

**Comment by palpapig** [comment]
Just notice the almighty Clang-format does not support C# in VScode. One more language for me to  create chaos.

**Comment by SKyletoft** [comment]
Shouldn't this just be adding C# to the list of supported languages?

**Comment by lonix1** [comment]
@xaverh I see that you merged the support for c# long ago. Please push the new version to the marketplace?

**Comment by somedeveloper00** [comment]
Hello! This was marked as solved 3 years ago but apparently the version at the marketplace currently doesn't support C#
<img width="613" height="697" alt="Image" src="https://github.com/user-attachments/assets/111c3701-139c-45b7-a714-52dc12d29c08" />
The marketplace notes that the latest update was at 2019-01-22 which is over 6 years ago. I know we can use the extension by cloning the repo and building it locally, so technically it's not a problem. But still, with over 2 million installs, would be a shame if the marketplace version is years behind the `master`. If there's anything we can do to make the process of publishing simpler, let us know! note that vscode has a "pre-release" mode for extensions too,  so if you don't want to spend time stabilizing all the new changes before publishing, you can just publish `master` as "pre-release" and call it a day!
